# tasks file for /home/dima/Desktop/ansible/roles/liferay
---



- name: Install PostgreSQL packages
  yum:
    name:
      - postgresql{{postgresql_version}}
      - postgresql{{postgresql_version}}-server
    state: present

- name: Give permission -R to postgres
  shell: chown -R postgres:postgres /usr/pgsql-{{ postgresql_version }}

- name: Install psycopg2
  shell: yum -y install python3-psycopg2

- name: Initialize PostgreSQL database
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql-12-setup initdb #-D /var/lib/pgsql/{{ postgresql_version }}/data
  
- name: Start PostgreSQL service
  systemd:
    name: postgresql-{{ postgresql_version }}
    state: started
    enabled: true


- name: Configure PostgreSQL
  become_user: postgres
  lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
    regexp: ^#?listen_addresses\s*=\s*'localhost'
    line: listen_addresses = '*'

- name: Configure 
  become_user: postgres
  lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
    regexp: ^#?port\s*=\s*5432
    line: port = 5432

 

- name: Restart PostgreSQL service
  become_user: postgres
  service: "name=postgresql-{{ postgresql_version }} state=started enabled=yes"
  #systemd:
   # name: postgresql-{{ postgresql_version }}
    #state: restarted


    